---

services:
  vaultwarden:
    image: fisher772/vaultwarden
    container_name: vaultwarden
    hostname: vaultwarden
    restart: unless-stopped
    volumes:
      - data:/data/
      - logs:/var/log/vaultwarden
      - nginx:/data/nginx
    environment:
      - TZ=${EKB}
      - LOG_FILE=${LOGS}
      - LE_FQDN=${FQDN}
      - SERVER_ALIAS=${ALIAS}
    networks:
      - nginx

networks:
  nginx:
    external: true

volumes:
  data:
  logs:
  nginx:
