---

services:
  vaultwarden:
    image: fisher772/vaultwarden
    container_name: vaultwarden
    hostname: vaultwarden
    restart: unless-stopped
    volumes:
      - data:/data/
      - ${N_CONF}:/data/nginx_conf
      - ${N_STREAM}:/data/nginx_stream
    environment:
      - TZ=${EKB}
      - LOG_FILE=${LOGS}
    networks:
      - nginx

networks:
  nginx:
    external: true

volumes:
  data:
