---

services:
  vaultwarden:
    image: fisher772/vaultwarden
    container_name: vaultwarden
    hostname: vaultwarden
    restart: unless-stopped
    volumes:
      - vaultwarden_data:/data/
      - vaultwarden_logs:/var/log/vaultwarden
      - vaultwarden_nginx:/data/nginx
    environment:
      - TZ=${EKB}
      - LOG_FILE=${LOGS}
      - LE_FQDN=${FQDN}
      - COUNTAINER_ALIAS=${C_ALIAS}
      - SERVER_ALIAS=${S_ALIAS}
    networks:
      - nginx

networks:
  nginx:
    external: true

volumes:
  data:
  logs:
  nginx:
