---

services:
  3x-ui:
    image: fisher772/3xui
    container_name: 3xui
    hostname: 3xui
    restart: unless-stopped
    ports:
      - '62222:62222'
      - '62333:62333'
    volumes:
      - db:/etc/x-ui
      - nginx_ssl:/root/cert
      - 3xui_nginx_conf:/data/nginx
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      LE_FQDN: ${FQDN}
      CONTAINER_ALIAS: ${C_ALIAS}
      SERVER_ALIAS: ${S_ALIAS}
    networks:
      - 3xui
      - nginx

networks:
  3xui:
  nginx:

volumes:
  db:
  nginx_ssl:
  xui_nginx_conf:
    name: 3xui_nginx_conf
