---

services:
  3x-ui:
    image: fisher772/3x-ui
    container_name: 3xui
    hostname: 3xui
    restart: unless-stopped
    ports:
      - '62222:62222'
      - '62333:62333'
    volumes:
      - db:/etc/x-ui/
      - cert:/root/cert/
      - nginx:/data/nginx
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      LE_FQDN: ${FQDN}
    networks:
      - 3xui
      - nginx

networks:
  3xui:
    external: true
  nginx:
    external: true
    

volumes:
  db:
  cert:
  nginx:
