---

services:
  3x-ui:
    image: fisher772/3x-ui
    container_name: 3x-ui
    hostname: 3x-ui
    restart: unless-stopped
    volumes:
      - db:/etc/x-ui/
      - cert:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    network_mode: host

volumes:
  db:
  cert:
