---

services:
  squid:
    image: fisher772/squid
    container_name: squid
    hostname: squid
    restart: always
    ports:
      - '8888:8888'
    volumes:
      - cache:/var/spool/squid
      - logs:/var/log
      - data:/etc/squid
    environment:
      - TZ=${EKB}
      - HTTP_PORT=${PORT}
      - DNS_VALUE=${DNS}
      #- TRUSTED_IP=${T_IP}
    networks:
      - nginx
      - squid

networks:
  squid:
    external: true
  nginx:
    external: true

volumes:
  cache:
  logs:
  data:
