---

services:
  squid:
    image: fisher772/squid
    container_name: squid
    hostname: squid
    restart: always
    ports:
      - '3128:3128'
    volumes:
      - cache:/var/spool/squid
      - logs:/var/log
      - data:/etc/squid
      - nginx:/data/nginx
    environment:
      - TZ=${EKB}
      - LE_FQDN=${FQDN}
      - SERVER_ALIAS=${ALIAS}
      #- TRUSTED_IP=${T_IP}
    networks:
      - nginx
      - squid

networks:
  squid:
  nginx:
    external: true

volumes:
  cache:
  logs:
  data:
  nginx:
