---

services:
  nginx:
    image: fisher/nginx-le
    container_name: nginx
    hostname: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '8080-8082:8080-8082'
      - '8443-8445:44301-44303'
    volumes:
      - ssl:/etc/nginx/ssl
      - conf:/etc/nginx
      - logs:/var/log/nginx
    environment:
      - TZ=${EKB}
      - LETSENCRYPT=${STATUS}
      - LE_EMAIL=${EMAIL}
      - LE_FQDN=${FQDN}
      #- SSL_CERT=le-crt.pem
      #- SSL_KEY=le-key.pem
      #- SSL_CHAIN_CERT=le-chain-crt.pem
      #- LE_ADDITIONAL_OPTIONS='--preferred-chain "ISRG Root X1"'
    networks:
      - nginx

networks:
  nginx:
    external: true

volumes:
  ssl:
  conf:
  logs:
