version: '3.0'
services:
  strongswan:
    image: fisherdevops/vpn-strongswan
    container_name: vpn-strongswan
    privileged: true
    network_mode: host
    environment:
      - IPTABLES=true
      - IPTABLES_INTERFACE=eth0
      - IPTABLES_ENDPOINTS=10.1.1.0/32
    volumes:
      - /lib/modules:/lib/modules:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/ipsec.d:/etc/ipsec.d:ro
      - /etc/xl2tpd:/etc/xl2tpd:ro
      - /etc/ppp:/etc/ppp:ro
