services:
  vpn-strongswan:
    image: fisherdevops/vpn-strongswan:v1
    container_name: vpn-strongswan
    privileged: true
    network_mode: host
    environment:
      - IPTABLES=${STATUS}
      - IPTABLES_INTERFACE=${NET}
      - IPTABLES_ENDPOINTS=${VPN_ROUTE_RANGE}
    volumes:
      - other:/etc/localtime:ro
      - ipsec.d:/etc/ipsec.d:rw
      - xl2tpd:/etc/xl2tpd:rw
      - ppp:/etc/ppp:rw

volumes:
  other:
  ipsec.d:
  xl2tpd:
  ppp:
