services:
  vpn-strongswan:
    image: fisher/vpn-strongswan
    container_name: vpn-strongswan
    privileged: true
    network_mode: host
    restart: always
    environment:
      - TZ=${EKB}
      - IPTABLES=${STATUS}
      - IPTABLES_INTERFACE=${NET}
      - IPTABLES_ENDPOINTS=${IPTAB_ROUTE_RANGE}
    volumes:
      - ipsec.d:/etc/ipsec.d:rw
      - xl2tpd:/etc/xl2tpd:rw
      - ppp:/etc/ppp:rw

volumes:
  ipsec.d:
  xl2tpd:
  ppp:
