---

services:
  vpn-strongswan:
    image: fisher/vpn-strongswan
    container_name: vpn-strongswan
    hostname: vpn-strongswan
    privileged: true
    network_mode: host
    restart: always
    volumes:
      - ipsec.d:/etc/ipsec.d
      - strongswan.d:/etc/strongswan.d
      - xl2tpd:/etc/xl2tpd
      - ppp:/etc/ppp
      - logs:/var/log/vpn
    environment:
      - TZ=${EKB}
      - LE_CERT_STATUS=${CERT_STATUS}
      - IPTABLES=${STATUS}
      - IPTABLES_INTERFACE=${NET}
      - IPTABLES_ENDPOINTS=${IPTAB_ROUTE_RANGE}

volumes:
  ipsec.d:
  strongswan.d:
  xl2tpd:
  ppp:
  logs:
